name: Jest test coverage
on: 
  push:
    branches: [ pull-request ]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci

      - name: Executar Testes
        run: npm run test:coverage

      - name: Verificar Cobertura
        run: |
          COVERAGE_FILE="./coverage/lcov-report/index.json"
          COVERAGE=$(cat $COVERAGE_FILE)
          LINES_PCT=$(echo $COVERAGE | jq -r '.total.lines.pct')
          STATEMENTS_PCT=$(echo $COVERAGE | jq -r '.total.statements.pct')

          if (( $(echo "$LINES_PCT < 100" | bc -l) )) || (( $(echo "$STATEMENTS_PCT < 100" | bc -l) )); then
            echo "A cobertura de testes não é de 100%."
            exit 1
          fi