name: Verificação de Cobertura de Teste

on: [pull_request]

jobs:
  test:
    name: Executar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Instalar dependências
        run: npm install

      - name: Executar Testes
        run: npm test -- --coverage

      - name: Verificar Cobertura
        run: |
          COVERAGE_FILE="./coverage/lcov-report/index.json"
          COVERAGE=$(cat $COVERAGE_FILE)
          LINES_PCT=$(echo $COVERAGE | jq -r '.total.lines.pct')
          STATEMENTS_PCT=$(echo $COVERAGE | jq -r '.total.statements.pct')

          if (( $(echo "$LINES_PCT < 100" | bc -l) )) || (( $(echo "$STATEMENTS_PCT < 100" | bc -l) )); then
            echo "A cobertura de testes não é de 100%."
            exit 1
          fi
