name: Jest test coverage
on: 
  push:
    branches: [ pull-request ]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Rodar os testes
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - name: Verificar cobertura
        run: |
          # Comando para coletar a porcentagem de cobertura do Jest
          coverage=$(npm run coverage -- --no-watch --json | jq '.total.lines.pct')

          if (( $(echo "$coverage < 100" | bc -l) )); then
            echo "A cobertura do Jest é menor que 100% (${coverage}%). O merge está bloqueado."
            exit 1
          fi
